---
- name: Initial Ubuntu Server Setup
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  roles:
    - common
    - deploy
    - ssh
    - ufw
    - unattended_upgrades
