---
- name: Ensure apt dependencies are installed
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    state: present
    update_cache: true

- name: Add Caddy GPG key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /tmp/caddy-key.gpg
    mode: "0644"

- name: Convert and install Caddy GPG key
  ansible.builtin.shell: gpg --dearmor < /tmp/caddy-key.gpg > /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  changed_when: false

- name: Add Caddy repository
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Remove temporary Caddy GPG key
  ansible.builtin.file:
    path: /tmp/caddy-key.gpg
    state: absent

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true

- name: Ensure caddy user and group exist
  ansible.builtin.user:
    name: caddy
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Ensure caddy group exists
  ansible.builtin.group:
    name: caddy
    system: true
    state: present

- name: Assign caddy group to caddy users
  ansible.builtin.user:
    name: "{{ item }}"
    groups: caddy
    append: true
  loop:
    - caddy
    - "{{ deploy_user_name }}"

- name: Ensure log directory exists
  ansible.builtin.file:
    path: "{{ caddy_server_log_dir }}"
    state: directory
    owner: caddy
    group: caddy
    mode: "0774"

- name: Ensure per-site Caddy log files exist
  ansible.builtin.file:
    path: "{{ caddy_server_log_dir }}/{{ item.title | default(item.domain) }}.log"
    state: touch
    owner: caddy
    group: caddy
    mode: "0644"
  loop: "{{ caddy_server_sites }}"

- name: Deploy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: caddy
    mode: "0640"
    validate: "caddy validate --adapter caddyfile --config %s"
  notify: Reload Caddy

- name: Ensure caddy service is enabled and started
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started
