---
- name: Set SSH allowed users dynamically
  ansible.builtin.set_fact:
    ssh_allowed_users:
      - "{{ deploy_user_name }}"
      - "{{ lookup('env', 'SERVER_USER') }}"
- name: Deploy hardened sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: "{{ ssh_config_path }}"
    owner: root
    group: root
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart ssh
