---

- name: Login to Vault and save token
  community.hashi_vault.vault_login:
    url: "https://127.0.0.1:8200"
    auth_method: userpass
    username: "{{ vault_admin_username }}"
    password: "{{ vault_admin_password }}"
  register: vault_login_result
  no_log: true

- name: Set Vault token as fact
  ansible.builtin.set_fact:
    vault_token: "{{ vault_login_result.login.auth.client_token }}"

- name: Ensure .config/containers/systemd directories exist
  ansible.builtin.file:
    path: "/home/{{ deploy_user_name }}/.config/containers/systemd"
    state: directory
    owner: "{{ deploy_user_name }}"
    group: "{{ deploy_user_name }}"
    mode: "0755"
    recurse: true

- name: Template the shared network file
  ansible.builtin.template:
    src: shared-network.network.j2
    dest: "/home/{{ deploy_user_name }}/.config/containers/systemd/shared-network.network"
    owner: "{{ deploy_user_name }}"
    group: "{{ deploy_user_name }}"
    mode: "0644"

- name: Reload systemd daemon for the shared network users
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ deploy_user_name }}"

- name: Start and enable the shared network
  ansible.builtin.systemd:
    name: shared-network-network.service
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ deploy_user_name }}"

- name: Create Postgres
  ansible.builtin.include_tasks: postgres.yml

