---
- name: Store PostgreSQL secrets in Vault
  community.hashi_vault.vault_kv2_write:
    url: https://127.0.0.1:8200
    token: "{{ vault_token }}"
    path: postgres
    data:
      POSTGRES_USER: "{{ psql_user }}"
      POSTGRES_PASSWORD: "{{ psql_pass }}"

- name: Restart Vault Agent
  ansible.builtin.systemd:
    name: vault-agent
    state: restarted

- name: Wait for Vault Agent to generate PostgreSQL environment file
  ansible.builtin.wait_for:
    path: "{{ vault_agent_secrets_dir }}/postgres.env"
    timeout: 60

- name: Create data directory for PostgreSQL
  ansible.builtin.file:
    path: "/home/{{ deploy_user_name }}/podman/postgres/data"
    state: directory
    owner: "{{ deploy_user_name }}"
    group: "{{ deploy_user_name }}"
    mode: "0755"
    recurse: true

- name: Template the PostgreSQL container file
  ansible.builtin.template:
    src: postgres.container.j2
    dest: "/home/{{ deploy_user_name }}/.config/containers/systemd/postgres.container"
    owner: "{{ deploy_user_name }}"
    group: "{{ deploy_user_name }}"
    mode: "0644"

- name: Reload systemd daemon for the deploy user
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ deploy_user_name }}"

- name: Start PostgreSQL container
  ansible.builtin.systemd:
    name: postgres.service
    enabled: true
    scope: user
  become: true
  become_user: "{{ deploy_user_name }}"
