---
- name: Check if vault is already installed
  ansible.builtin.stat:
    path: "{{ vault_install_dir }}/vault"
  register: vault_installed

- name: Include Vault user tasks
  ansible.builtin.include_tasks: user.yml
  when: not vault_installed.stat.exists

- name: Include Vault installation tasks
  ansible.builtin.include_tasks: install.yml
  when: not vault_installed.stat.exists

- name: Include Vault configuration tasks
  ansible.builtin.include_tasks: configure.yml
  when: not vault_installed.stat.exists

- name: Include Vault authentication configuration tasks
  ansible.builtin.include_tasks: auth_conf.yml
  when: not vault_installed.stat.exists

- name: Include Vault agent tasks
  ansible.builtin.include_tasks: agent.yml
  when: not vault_installed.stat.exists
