---
- name: Ensure Vault group exists
  ansible.builtin.group:
    name: "{{ vault_group }}"
    state: present
    system: true

- name: Ensure Vault user exists
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    create_home: false
    shell: /usr/sbin/nologin
    system: true

- name: Include Vault installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Include Vault configuration tasks
  ansible.builtin.include_tasks: configure.yml
