---
- name: Ensure Vault group exists
  ansible.builtin.group:
    name: "{{ vault_group }}"
    state: present
    system: true

- name: Ensure Vault user exists
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    # create_home: false
    # shell: /usr/sbin/nologin #TODO: uncomment later
    system: true

- name: Add Deploy user to Vault group
  ansible.builtin.user:
    name: "{{ deploy_user_name }}"
    groups: "{{ vault_group }}"
    append: true

- name: Enable lingering for the vault user
  ansible.builtin.command: "loginctl enable-linger vault"
  changed_when: false
  failed_when: false
  notify: Reload systemd daemon for user
