---
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"

- name: Add hostname to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127\\.0\\.1\\.1.*"
    line: "127.0.1.1 {{ server_hostname }}"
    owner: root
    group: root
    mode: "0644"

- name: Install common packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - unzip
      - htop
      - vim
      - logrotate
      - acl
    state: present
