---
- name: Reload UFW rules
  ansible.builtin.command: ufw reload
  listen: Reload ufw

- name: Restart UFW service
  ansible.builtin.service:
    name: ufw
    state: restarted
  listen: Reload ufw
