---
- name: Restart podman user socket
  ansible.builtin.systemd:
    name: podman.socket
    scope: user
    state: restarted
  become: true
  become_user: "{{ deploy_user_name }}"
  listen: restart podman user socket

- name: Enable podman user socket
  ansible.builtin.systemd:
    name: podman.socket
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ deploy_user_name }}"
  listen: enable podman user socket
