---
vault_version: "latest"
vault_download_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
vault_install_dir: "/usr/local/bin"
vault_user: "vault"
vault_group: "vault"
vault_config_dir: "/etc/vault.d"
vault_tls_cert_file: "{{ vault_config_dir }}/vault.crt"
vault_tls_key_file: "{{ vault_config_dir }}/vault.key"
vault_data_dir: "/opt/vault"
vault_secret_dest_dir: "/var/vault/secrets"
vault_runtime_dir: "secrets/vault"

vault_admin_username: "{{ vault_admin_username }}"
vault_admin_password: "{{ vault_admin_password }}"

# Vault Agent configuration
vault_agent_config_dir: "/etc/vault-agent.d"
vault_agent_data_dir: "/opt/vault-agent"
vault_agent_secrets_dir: "/var/vault/secrets"
vault_agent_user: "vault"
vault_agent_group: "vault"

# Vault Agent secrets to template
vault_agent_secrets: # NOTE: This is a placeholder for now, later on this needs to be populated with all the secrets that need to be templated
  - path: "secret/data/postgres"
    output_file: "postgres.env"
  - path: "secret/data/minio"
    output_file: "minio.env"
